/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hawk007_com_androidcode_jni_MyNdk */

#ifndef _Included_hawk007_com_androidcode_jni_MyNdk
#define _Included_hawk007_com_androidcode_jni_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hawk007_com_androidcode_jni_MyNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hawk007_com_androidcode_jni_MyNdk_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
